"""Render PR #26 follow-up outputs into LaTeX macros for supplementary use.

Usage:
    uv run python scripts/render_pr26_followups_tex.py \
      --followup-dir data/post_hoc/pr26_followups \
      --output paper/generated/pr26_followups.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text())


def _fmt_float(value: object) -> str:
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return f"{float(value):.4f}"
    return "N/A"


def _fmt_pct(value: object) -> str:
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return f"{float(value) * 100.0:.2f}"
    return "N/A"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Render follow-up results into TeX macros")
    parser.add_argument("--followup-dir", type=Path, default=Path("data/post_hoc/pr26_followups"))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/generated/pr26_followups.tex"),
    )
    args = parser.parse_args(argv)

    base = Path(args.followup_dir)
    no_filter = _load_json(base / "no_filter" / "summary.json")
    sync = _load_json(base / "synchronous_ablation" / "summary.json")
    ranking = _load_json(base / "ranking_stability" / "summary.json")
    te_null = _load_json(base / "te_null" / "summary.json")
    phenotypes = _load_json(base / "phenotypes" / "taxonomy.json")
    manifest = _load_json(base / "manifest.json")

    ranking_rows = ranking.get("pairwise_kendall_tau", {})
    phase2_rows = ranking_rows.get("2", [])
    taus = [
        float(row["kendall_tau"])
        for row in phase2_rows
        if isinstance(row, dict) and isinstance(row.get("kendall_tau"), (int, float))
    ]
    tau_median = sorted(taus)[len(taus) // 2] if taus else float("nan")

    te_phase2 = te_null.get("conditions", {}).get("phase_2", {})
    phenotype_counts = phenotypes.get("counts", {})
    dominant_label = "unknown"
    dominant_count = -1
    if isinstance(phenotype_counts, dict):
        for label, count in phenotype_counts.items():
            if isinstance(count, int) and count > dominant_count:
                dominant_label = str(label)
                dominant_count = count
    dominant_label_tex = dominant_label.replace("_", "\\_")
    dominant_count_text = str(dominant_count) if dominant_count >= 0 else "N/A"
    sync_phase_count = len(sync.get("phase_pairwise", {}))
    manifest_doi = (manifest.get("zenodo") or {}).get("doi", "N/A")

    lines = [
        "% Auto-generated by scripts/render_pr26_followups_tex.py",
        f"% source: {base}",
        f"\\newcommand{{\\PrTwentySixManifestCommit}}{{{manifest.get('git_commit', 'unknown')}}}",
        f"\\newcommand{{\\PrTwentySixManifestDoi}}{{{manifest_doi}}}",
        f"\\newcommand{{\\PrTwentySixFilteredSurvivalPct}}{{{_fmt_pct(no_filter.get('filtered_survival_rate'))}}}",
        f"\\newcommand{{\\PrTwentySixNoFilterSurvivalPct}}{{{_fmt_pct(no_filter.get('no_filter_survival_rate'))}}}",
        f"\\newcommand{{\\PrTwentySixPhaseTwoKendallTauMedian}}{{{_fmt_float(tau_median)}}}",
        f"\\newcommand{{\\PrTwentySixPhaseTwoTeMedian}}{{{_fmt_float(te_phase2.get('te_median'))}}}",
        f"\\newcommand{{\\PrTwentySixPhaseTwoTeNullMedian}}{{{_fmt_float(te_phase2.get('te_null_median'))}}}",
        f"\\newcommand{{\\PrTwentySixPhaseTwoTeExcessMedian}}{{{_fmt_float(te_phase2.get('te_excess_median'))}}}",
        f"\\newcommand{{\\PrTwentySixDominantPhenotype}}{{{dominant_label_tex}}}",
        f"\\newcommand{{\\PrTwentySixDominantPhenotypeCount}}{{{dominant_count_text}}}",
        f"\\newcommand{{\\PrTwentySixSynchronousPhaseCount}}{{{sync_phase_count}}}",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
